# Generated by rspec-sinatra. (2015-06-29 15:07:42 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', 'app/bookmarks_web.rb')

require 'capybara'
require 'capybara/rspec'
require 'database_cleaner'
require 'rspec'

require './app/data_mapper_setup.rb'

Capybara.app = BookmarksWeb

RSpec.configure do |config|

 config.before(:suite) do
   DatabaseCleaner.strategy = :transaction
   DatabaseCleaner.clean_with(:truncation)
 end

 config.before(:each) do
   DatabaseCleaner.start
 end

 config.after(:each) do
   DatabaseCleaner.clean
 end

 config.include Capybara::DSL

 config.expect_with :rspec do |expectations|
   expectations.include_chain_clauses_in_custom_matcher_descriptions = true
 end

 config.mock_with :rspec do |mocks|
   mocks.verify_partial_doubles = true
 end
end
